description: Successfully list of exchange sub account ids
content:
  application/json:
    schema:
      type: array
      items:
        $ref: '../../../schemas/wallets/exchanges/exchange_settings.yaml'