type: object
description: The data for project information.
properties:
  id:
    type: string
    example: "0111039d-27fb-49ba-b172-6e0aa80e37ec"
    description: The project ID.
  org_id:
    type: string
    example: "f3b4a616-9c43-462e-8cb4-343e304fee64"
    description: The Organization ID.
  name:
    type: string
    example: 'Project name'
    description: The project name.
  node_count:
    type: integer
    example: 3
    description: The number of key share holders in the project.
  threshold:
    type: integer
    example: 2
    description: The number of key share holders required to sign an operation in the project.
  create_timestamp:
    type: integer
    format: int64
    example: 1718619403933.53
    description: The project's creation time in Unix timestamp format, measured in milliseconds.