get:
  tags:
    - Wallets - MPC Wallet
  operationId: get_mpc_project
  summary: Get a mpc project information
  description: |
    Get detailed information about a mpc project identified by its unique ID. 
    
    Get project ids by calling list_mpc_project. 

    Error codes this API may return:
    | Error Code | Description |
    | -- | -- |
    | `2006` | 参数格式或者值非法 |
  security:
    - CoboAuth: []
  parameters:
    - $ref: "../../../components/parameters/wallets/mpcs/project_id_path.yaml"
  responses:
    '200':
      $ref: "../../../components/responses/wallets/mpcs/get_project.yaml"
    '400':
      $ref: "../../../components/responses/errors/400_bad_request.yaml"
    '404':
      $ref: "../../../components/responses/errors/404_not_found.yaml"
    '503':
      $ref: "../../../components/responses/errors/503_service_unavailable.yaml"
put:
  tags:
    - Wallets - MPC Wallet
  operationId: update_mpc_project
  summary: Update a mpc project
  description: |
    Update a mpc project name information by its ID. 

    Error codes this API may return:
    | Error Code | Description |
    | -- | -- |
    | `2006` | 参数格式或者值非法 |
  security:
    - CoboAuth: []
  parameters:
    - $ref: "../../../components/parameters/wallets/mpcs/project_id_path.yaml"
  requestBody:
    $ref: "../../../components/request_bodies/wallets/mpcs/update_project.yaml"
  responses:
    '200':
      $ref: "../../../components/responses/wallets/mpcs/get_project.yaml"
    '400':
      $ref: "../../../components/responses/errors/400_bad_request.yaml"
    '404':
      $ref: "../../../components/responses/errors/404_not_found.yaml"
    '503':
      $ref: "../../../components/responses/errors/503_service_unavailable.yaml"

